[theme]
base="light"
primaryColor="#f63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
maxMessageSize = 500
enableCORS = false
enableXsrfProtection = false
